# Generated by Django 4.1.1 on 2022-09-29 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id_livro', models.UUIDField(default=uuid.UUID('ca10bb52-be9a-471e-8998-96fe5e272312'), editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=60)),
                ('ano_lancamento', models.IntegerField()),
                ('condicao', models.CharField(max_length=30)),
                ('paginas_qtd', models.IntegerField()),
                ('editora', models.CharField(max_length=80)),
                ('qnd_criado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
